kind: Service
apiVersion: v1
metadata:
  name: expose-kafka-manager
  namespace: kafka
spec:
  selector:
    app: kafka-manager
  externalTrafficPolicy: Local
  ports:
  - protocol: TCP
    targetPort: 80
    port: 30080
    nodePort: 30080
  type: NodePort
