kind: Service
apiVersion: v1
metadata:
  name: expose-kafka-broker
  namespace: kafka
spec:
  selector:
    app: kafka
    kafka-broker-id: "0"
  externalTrafficPolicy: Local
  ports:
  - protocol: TCP
    targetPort: 9094
    port: 32400
    nodePort: 32400
  type: NodePort
